%% @config(../mindmap-config.json)
mindmap
    Chef de formation
        Ce qu'il fait
            J'imprime décision des Congés.
        Ce qu'il dit
            J'utilise Microsoft Word pour imprimer les decision des Congés.
