%% @config(../mindmap-config.json)
mindmap
    Directeur générale
        Ce qu'il fait
            J'utilise Google Sheets pour suivre les données de congé.
            J'utilise Microsoft Word pour remplir et imprimer les decision des Congés.
        Ce qu'il dit
            calculer jour reaston.
            J'imprime décision des Congés.
