%% @config(../mindmap-config.json)
mindmap
    Directeur_pkg_Absences
        Ce qu'il fait
            Utilise Excel pour maintenir une gestion organisée et cohérente des absences.
        Ce qu'il dit
            Il veut suivre les absences par tous les établissements.