%% @config(../mindmap-config.json)
mindmap
    Chef de formation_Absences
        Ce qu'il fait
            J'utilise Google Sheets pour suivre les absences de chaque employé.
            J'utilise Microsoft Word pour remplir et imprimer les maquettes d'absentéisme.
        Ce qu'il dit
            Je transmets la liste des absents des employés du centre chaque mois.